[controller]
worker01 ansible_host=192.168.1.110

[workers]
worker01 ansible_host=192.168.1.110
worker02 ansible_host=192.168.1.103

[cluster:children]
controller
workers

[cluster:vars]
ansible_user=cluster
ansible_python_interpreter=/usr/bin/python3